# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fde0eac9ebe9eb228bfa1f9e2b9fc82c20856fdda3e6ee772eb61777e0e95dd2c69b620fdd38ca98e7e69d92a54481ff74b9b39851727505822fb7323a999c3c

test:
  secret_key_base: 2f64bdfd9c301905f7ee4416a7b17d6dca71d9f20a8d66cab2eeff9c1351a5da71c92b8fa229829de7655a97302022cdfbceafe25819489ba80df32b255c69ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
